use WebAssignment2;

-- CREATE CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
    customerID INT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(12) NOT NULL
);

-- CREATE APPLIANCES TABLE
CREATE TABLE APPLIANCES (
    applianceID INT AUTO_INCREMENT PRIMARY KEY,
    applianceName VARCHAR(255) NOT NULL,
    applianceType VARCHAR(255) NOT NULL
);

-- CREATE CUST_APPLIANCES JUNCTION TABLE
CREATE TABLE CUST_APPLIANCES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    customerID INT,
    applianceID INT,
    CONSTRAINT FK_CUSTOMER_APPLIANCE FOREIGN KEY (applianceID) REFERENCES APPLIANCES(applianceID),
    CONSTRAINT FK_APPLIANCE_CUSTOMER FOREIGN KEY (customerID) REFERENCES CUSTOMERS(customerID)
);

-- CREATE TECHNICIANS TABLE
CREATE TABLE TECHNICIANS (
    technicianID INT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL
);

-- CREATE APPOINTMENTS TABLE
CREATE TABLE APPOINTMENTS (
    appointmentID INT AUTO_INCREMENT PRIMARY KEY,
    applianceID INT,
    technicianID INT,
    customerID INT,
    appointmentDateTime DATETIME NOT NULL,
    reason NVARCHAR(500) NULL,
    quote DECIMAL(10,2),
    CONSTRAINT FK_APPOINTMENT_APPLIANCE FOREIGN KEY (applianceID) REFERENCES APPLIANCES(applianceID),
    CONSTRAINT FK_APPOINTMENT_TECHNICIAN FOREIGN KEY (technicianID) REFERENCES TECHNICIANS(technicianID),
    CONSTRAINT FK_APPOINTMENT_CUSTOMER FOREIGN KEY (customerID) REFERENCES CUSTOMERS(customerID)
);


